services:
  - type: web
    name: gmu-rpms
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
