services:
  - type: web
    name: rpms
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
      - key: SESSION_DRIVER
        value: database
