services:
  - type: web
    name: research-project-management-system
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: GMU-RPMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        value: base64:d19mTWFnZWMxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
